<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_1_loginNegative</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>48f4424e-7013-4cf5-a54e-58c2fcbfe796</testSuiteGuid>
   <testCaseLink>
      <guid>fe7b1109-7833-49e5-93a6-b7c55b364588</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Web/Negative Case/TC_001_2_Login_Negative_Invalid_Organization_Name</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59da944d-3149-460d-9e81-168891e4f014</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a26956e4-efc6-4b4b-be41-ae412b9cb654</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Web/Negative Case/TC_002_2_Login_Negative_Empty_UsernameAndPassword</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82a3cb74-9db7-4396-a170-f8dbe44d0e04</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a771e7f7-5457-4f47-8896-010d64e94a43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5733a51f-6973-4129-89ef-87e3fb95003a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8505e874-98c8-4ef1-ad03-a1c41c082903</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Web/Negative Case/TC_003_2_Login_Negative_Empty_Password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14e28b00-45f8-4527-8d25-262dc842bee3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>706cd1b2-ef65-4449-a427-bb01eb2f2c6d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06e9354d-21fb-4d66-b9eb-95dc010c0582</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6f2d2fe4-a888-4950-ab77-9608a419c21e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Web/Negative Case/TC_004_2_Login_Negative_Empty_Username</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8716d8ca-916b-4a3d-b0ad-7c9a69e98366</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd2a988a-9148-498a-a724-6448256fc3b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1da941db-bca0-4e91-98ed-121aded71a92</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e2a65a98-14c4-4703-8f96-08f446334f85</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Web/Negative Case/TC_005_2_Login_Negative_Least_Password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8015fa1-760e-4372-aece-96371f6896f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>029feee5-5621-411b-bc31-45fb17fa0b06</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1091da26-4ca9-4beb-98bc-9245c740fe3c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
